# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: ovh-cli
    binary: ovhcloud
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -extldflags -static -X github.com/ovh/ovhcloud-cli/internal/version.Version={{.Tag}}
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/ovhcloud

  - id: ovh-cli-wasm
    binary: ovhcloud
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -extldflags -static -X github.com/ovh/ovhcloud-cli/internal/version.Version={{.Tag}}
    goos:
      - js
    goarch:
      - wasm
    main: ./cmd/ovhcloud

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      ids:
        - ovh-cli
      sign:
        certificate: "{{ .Env.MACOS_SIGN_P12 }}"
        password: "{{ .Env.MACOS_SIGN_PASSWORD }}"
      notarize:
        issuer_id: "{{ .Env.MACOS_NOTARY_ISSUER_ID }}"
        key_id: "{{ .Env.MACOS_NOTARY_KEY_ID }}"
        key: "{{ .Env.MACOS_NOTARY_KEY }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  mode: keep-existing
  replace_existing_artifacts: true

homebrew_casks:
  - name: ovhcloud-cli
    binary: ovhcloud
    url:
      template: "https://github.com/ovh/ovhcloud-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    repository:
      owner: ovh
      name: homebrew-tap
    commit_author:
      name: "ovh-cds"
      email: "ovh-cds@users.noreply.github.com"
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Casks
    caveats: "See https://github.com/ovh/ovhcloud-cli for usage."
    homepage: "https://github.com/ovh/ovhcloud-cli"
    description: "OVHcloud CLI - Command line interface for OVHcloud."
